export const GET_ITEMS_REQUESTED: string = "GET_ITEMS_REQUESTED";
export const GET_FILTERS_REQUESTED: string = "GET_FILTERS_REQUESTED";
export const GET_SEARCHED_ITEMS_REQUESTED: string = "GET_SEARCHED_ITEMS_REQUESTED";
export const GET_BRAND_FILTER_REQUESTED: string = "GET_SEARCHED_BRAND_REQUESTED";
export const GET_TAG_FILTER_REQUESTED: string = "GET_SEARCHED_TAG_REQUESTED";
export const GET_SORTING_FILTER_REQUESTED: string = "GET_SORTING_FILTER_REQUESTED";
export const GET_PAGINATION_REQUESTED: string = "GET_PAGINATION_REQUESTED";
export const GET_ITEM_TYPE_FILTER_REQUESTED: string = "GET_ITEM_TYPE_FILTER_REQUESTED";